services:
  postgres:
    image: postgres:15
    container_name: nfe_postgres
    environment:
      POSTGRES_DB: nfenodedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/Nfe.Infrastructure/Data/migrations/createClientesTable.sql:/docker-entrypoint-initdb.d/01-create-clientes.sql
      - ./src/Nfe.Infrastructure/Data/migrations/createProdutosTable.sql:/docker-entrypoint-initdb.d/02-create-produtos.sql
      - ./src/Nfe.Infrastructure/Data/seeds/seedClientes.sql:/docker-entrypoint-initdb.d/03-seed-clientes.sql
      - ./src/Nfe.Infrastructure/Data/seeds/seedProdutos.sql:/docker-entrypoint-initdb.d/04-seed-produtos.sql
    networks:
      - nfe-network

  api:
    build: .
    container_name: nfe_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_NAME=nfenodedb
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - nfe-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nfe_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - nfe-network

volumes:
  postgres_data:

networks:
  nfe-network:
    driver: bridge